import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "@/providers/Providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Luxenta AI Fund",
	description: "Generated by Luxenta AI Fund",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="bn" data-arp="">
			<body
				data-new-gr-c-s-check-loaded="14.1254.0"
				data-gr-ext-installed=""
				cz-shortcut-listen="true"
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[radial-gradient(75%_60%_at_20%_20%,#101a33_0%,#0a0f1c_35%,#060a14_100%)] `}>
				{" "}
				<Providers>
					<Toaster richColors position="top-center" />
					{children}
				</Providers>
			</body>
		</html>
	);
}
